import pathlib
p = pathlib.Path(r'C:\Tabrez\docx-html\docx-to-html\output\html_renderer.py')
t = p.read_text(encoding='utf-8')
old = '''        "    function layoutDecimalTabs(){\\n"
        "      document.querySelectorAll('.docx-tab-segment[data-val=\\\\\\"decimal\\\\\\"]').forEach(function(seg){\\n"
        "        var pos=parseInt(seg.getAttribute('data-pos'),10);\\n"
        "        if(isNaN(pos)) return;\\n"
        "        var text=seg.textContent||'';\\n"
        "        var dotIdx=text.indexOf('.');\\n"
        "        if(dotIdx===-1){\\n"
        "          seg.style.transform=\\"translateX(-100%)\\";\\n"
        "          return;\\n"
        "        }\\n"
        "        try{\\n"
        "          var walker=document.createTreeWalker(seg, NodeFilter.SHOW_TEXT, null, false);\\n"
        "          var node, targetNode=null, localIdx=-1;\\n"
        "          while(node=walker.nextNode()){\\n"
        "            var t=node.textContent;\\n"
        "            var idx=t.indexOf('.');\\n"
        "            if(idx!==-1){ targetNode=node; localIdx=idx; break; }\\n"
        "          }\\n"
        "          if(!targetNode){ seg.style.transform=\\"translateX(-100%)\\"; return; }\\n"
        "          var range=document.createRange();\\n"
        "          range.setStart(targetNode, localIdx);\\n"
        "          range.setEnd(targetNode, localIdx+1);\\n"
        "          var rect=range.getBoundingClientRect();\\n"
        "          var segRect=seg.getBoundingClientRect();\\n"
        "          var decimalOffset=rect.left - segRect.left;\\n"
        "          var newLeft=pos - decimalOffset;\\n"
        "          seg.style.left=newLeft+\\"px\\";\\n"
        "          seg.style.transform=\\"none\\";\\n"
        "        }catch(e){ seg.style.transform=\\"translateX(-100%)\\"; }\\n"
        "      });\\n"
        "    }\\n"'''
new = '''        "    function layoutDecimalTabs(){\\n"
        "      document.querySelectorAll('.docx-tab-segment[data-val=\\\\\\"decimal\\\\\\"]').forEach(function(seg){\\n"
        "        var pos=parseInt(seg.getAttribute('data-pos'),10);\\n"
        "        if(isNaN(pos)) return;\\n"
        "        var text=seg.textContent||'';\\n"
        "        var dotIdx=text.indexOf('.');\\n"
        "        if(dotIdx===-1){\\n"
        "          seg.style.transform=\\"translateX(-100%)\\";\\n"
        "          return;\\n"
        "        }\\n"
        "        try{\\n"
        "          var walker=document.createTreeWalker(seg, NodeFilter.SHOW_TEXT, null, false);\\n"
        "          var node, targetNode=null, localIdx=-1;\\n"
        "          while(node=walker.nextNode()){\\n"
        "            var t=node.textContent;\\n"
        "            var idx=t.indexOf('.');\\n"
        "            if(idx!==-1){ targetNode=node; localIdx=idx; break; }\\n"
        "          }\\n"
        "          if(!targetNode){ seg.style.transform=\\"translateX(-100%)\\"; return; }\\n"
        "          var range=document.createRange();\\n"
        "          range.setStart(targetNode, localIdx);\\n"
        "          range.setEnd(targetNode, localIdx+1);\\n"
        "          var rect=range.getBoundingClientRect();\\n"
        "          var segRect=seg.getBoundingClientRect();\\n"
        "          var p=seg.parentElement;\\n"
        "          while(p && p.tagName!=='P') p=p.parentElement;\\n"
        "          if(!p) p=seg.parentElement;\\n"
        "          var pRect=p.getBoundingClientRect();\\n"
        "          var segOffset=segRect.left - pRect.left;\\n"
        "          var decimalOffset=rect.left - pRect.left;\\n"
        "          var innerOffset=decimalOffset - segOffset;\\n"
        "          var newLeft=pos - innerOffset;\\n"
        "          seg.style.left=newLeft+\\"px\\";\\n"
        "          seg.style.transform=\\"none\\";\\n"
        "        }catch(e){ seg.style.transform=\\"translateX(-100%)\\"; }\\n"
        "      });\\n"
        "    }\\n"'''
if old in t:
    t = t.replace(old, new)
    p.write_text(t, encoding='utf-8')
    print('fixed decimal paragraph')
else:
    print('not found decimal JS old')
    import re
    for m in re.finditer(r'layoutDecimalTabs', t):
        print(repr(t[m.start()-300:m.start()+1000]))
