"""Font-size fidelity tests: model resolution + real browser verification.

Two layers of verification, both against a single real OOXML fixture
(tests/fixtures/font-fidelity.docx, generated by tests/create_font_fidelity_fixture.py):

1. test_font_fidelity_model -- pure model check. Runs the converter and asserts
   the EFFECTIVE ResolveStyle/Run half-point font size for each marker, proving
   the precedence (direct > character style > paragraph style > docDefaults) is
   correct without a browser.

2. test_font_fidelity_browser -- real Chromium. Uploads the fixture through the
   actual product UI, waits for the preview iframe, measures each marker's
   getComputedStyle(fontSize) in CSS pixels, reconstructs points (px * 72 / 96),
   and asserts the reconstruction matches the OOXML effective size within 0.01pt.
   This catches renderer/CSS bugs the model layer cannot see.

Expected OOXML effective sizes (half-points) are derived from the fixture, not
hardcoded from the converter output: every marker explicitly documents its source
of truth in the comments below.
"""

import os
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

import pytest  # noqa: E402

from core.model import Table  # noqa: E402
from semantic.pipeline import convert_docx  # noqa: E402

FIXTURE = os.path.join(PROJECT_ROOT, "tests", "fixtures", "font-fidelity.docx")

# Marker text -> expected effective font size in OOXML HALF-POINTS.
# Source of truth for each value (see create_font_fidelity_fixture.py):
#   SZ19..SZ56 : direct w:sz on the run (9.5pt..28pt)
#   PLAIN      : docDefaults rPrDefault sz=22 (11pt) -- no run/style size
#   PARA12     : paragraph style Para12 w:rPr sz=24 (12pt)
#   OVERRIDE16 : direct w:sz=32 (16pt) on a Para12 run -> direct wins
#   CHAR135    : character style Char135 w:rPr sz=27 (13.5pt)
#   CHARBOLD12 : char style CharBold (NO size) in Para12 -> inherits Para12 24 (12pt)
#   HEADING18  : paragraph style Heading1 sz=36 (18pt)
#   LIST11     : list item, docDefaults 22 (11pt)
#   TABLE11    : table cell run, docDefaults 22 (11pt)
#   HYPER11    : hyperlink run, docDefaults 22 (11pt)
#   MX19/MX28/MX48 : direct w:sz 19/28/48 in one paragraph
EXPECTED_HALF_POINTS = {
    "SZ19": 19, "SZ21": 21, "SZ22": 22, "SZ23": 23, "SZ24": 24,
    "SZ27": 27, "SZ28": 28, "SZ32": 32, "SZ36": 36, "SZ48": 48, "SZ56": 56,
    "PLAIN": 22, "PARA12": 24, "OVERRIDE16": 32, "CHAR135": 27,
    "CHARBOLD12": 24, "HEADING18": 36, "LIST11": 22, "TABLE11": 22,
    "HYPER11": 22, "MX19": 19, "MX28": 28, "MX48": 48,
}


def _find_run_font_size(result, marker):
    """Deep search for a run whose text contains `marker`; return font_size (half-pts)."""
    for para in result.paragraphs:
        for r in para.runs:
            if marker in (r.text or ""):
                return r.font_size
    for blk in result.blocks:
        if isinstance(blk, Table):
            for row in blk.rows:
                for cell in row.cells:
                    for p in cell.content:
                        for r in p.runs:
                            if marker in (r.text or ""):
                                return r.font_size
    for sec in (getattr(result, "header", None), getattr(result, "footer", None)):
        if not sec:
            continue
        for blk in sec.blocks:
            if isinstance(blk, Table):
                for row in blk.rows:
                    for cell in row.cells:
                        for p in cell.content:
                            for r in p.runs:
                                if marker in (r.text or ""):
                                    return r.font_size
    return None


def test_font_fidelity_model():
    """Effective half-point font size matches OOXML ground truth for every marker."""
    if not os.path.exists(FIXTURE):
        pytest.skip("fixture missing; run tests/create_font_fidelity_fixture.py")
    result = convert_docx(FIXTURE)
    failures = []
    for marker, expected in EXPECTED_HALF_POINTS.items():
        got = _find_run_font_size(result, marker)
        if got != expected:
            failures.append("%s: expected=%s got=%s" % (marker, expected, got))
    assert not failures, "font-size resolution failures:\n" + "\n".join(failures)


def test_font_fidelity_browser():
    """Browser-computed size reconstructs to OOXML effective size within 0.01pt."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        pytest.skip("playwright not installed")
    if not os.path.exists(FIXTURE):
        pytest.skip("fixture missing; run tests/create_font_fidelity_fixture.py")

    import threading
    from ui import web

    srv = web.make_server(host="127.0.0.1", port=0)
    threading.Thread(target=srv.serve_forever, daemon=True).start()
    base = "http://127.0.0.1:%d" % srv.server_address[1]

    # Half-points -> expected points for reconstruction check.
    expected_pt = {m: hp / 2.0 for m, hp in EXPECTED_HALF_POINTS.items()}

    with sync_playwright() as pw:
        browser = pw.chromium.launch()
        page = browser.new_page()
        console_errors = []
        page.on("console", lambda m: console_errors.append(m.text)
                if m.type == "error" else None)
        page.goto(base + "/")
        page.wait_for_selector("input[type=file]", timeout=10000)
        page.set_input_files("input[type=file]", FIXTURE)
        page.click("button[type=submit]")
        # The POST /upload response embeds the preview inline (same page).
        frame = page.frame_locator("iframe.preview")
        frame.locator(".docx-content").wait_for(timeout=15000)

        failures = []
        for marker, pt in expected_pt.items():
            # Locate the innermost element bearing the marker text, scoped to
            # .docx-content (the UI title bar outside it must not be measured).
            el = frame.locator(".docx-content").get_by_text(marker, exact=False).first
            el.wait_for(timeout=10000)
            # getComputedStyle(fontSize) -> "Npx"; px * 72/96 = pt.
            px = float(el.evaluate(
                "el => parseFloat(getComputedStyle(el).fontSize)"))
            got_pt = px * 72.0 / 96.0
            err = abs(got_pt - pt)
            if err > 0.01:
                failures.append("%s: expected=%.4fpt got=%.4fpt (px=%.3f, err=%.4f)"
                                % (marker, pt, got_pt, px, err))
        browser.close()

    assert not console_errors, "console errors:\n" + "\n".join(console_errors)
    assert not failures, "browser font-size fidelity failures:\n" + "\n".join(failures)
